version: '3.7'

services:
  www:
    build: .
    ports:
      - 80:80
    volumes:
      - ./www:/var/www/html

  db:
    image: mariadb
    restart: always
    command: "mysqld --innodb-flush-method=fsync"
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./db:/var/lib/mysql
      - ./db.init:/docker-entrypoint-initdb.d

  adminer:
    image: adminer
    restart: always
    ports:
      - 3000:8080
