version: '3.7'

services:
  www:
    build: .
    ports:
      - 80:80
    volumes:
      - ./www:/var/www/html

  db:
    image: linuxserver/mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./custom.cnf:/config/custom.cnf
      - ./db:/config/databases
      - ./db.init:/config/initdb.d

  adminer:
    image: adminer
    restart: always
    ports:
      - 3000:8080
