version: '3.7'

services:
  www:
    build: .
    restart: always
    ports:
      - 8080:80
    volumes:
      - ./www:/var/www/html
    secrets:
      - hackerearth_api_secret
      - database_password

  db:
    image: linuxserver/mariadb
    restart: always
    environment:
      FILE__MYSQL_ROOT_PASSWORD: /run/secrets/database_password
    volumes:
      - ./custom.cnf:/config/custom.cnf
      - ./db:/config/databases
      - ./db.init:/config/initdb.d
    secrets:
      - database_password

  adminer:
    image: adminer
    restart: always
    ports:
      - 3000:8080

secrets:
  hackerearth_api_secret:
    file: ./secrets/hackerearth_api_secret
  database_password:
    file: ./secrets/database_password