version: '3.7'

services:
  www:
    build: .
    ports:
      - 5000:80
    volumes:
      - ./www:/var/www/html

  db:
    image: bitnami/mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: password
    ports:
      - 3306:3306
    volumes:
      - ./db.init:/docker-entrypoint-initdb.d
      - ./db:/bitnami/mariadb

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8080:80
